services:
  - type: web
    name: news-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # use production-ready server
    plan: free

cronjobs:
  - name: scrape-news
    schedule: "hourly"
    command: "python scraper.py"
    plan: free
