name: Run Scraper Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'  # every 20 minutes
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper.py
        run: python scraper.py

      - name: Commit and Push updated news.json
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add news.json
          git push https://Mafiaboy2002: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@github.com/Mafiaboy2002/news-api.git
          git commit -m "Update news.json" || echo "No changes to commit"
