name: Run Scraper Every 20 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'  # every 20 minutes
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper.py
        run: python scraper.py

      - name: Pull the latest changes from the remote
        run: git pull origin main

      - name: Commit and Push updated news.json
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add news.json
          git commit -m "Update news.json" || echo "No changes to commit"
          git push https://Mafiaboy2002:${{ secrets.SCRAPER_TOKEN }}@github.com/Mafiaboy2002/news-api.git
        env:
          GITHUB_TOKEN: ${{ secrets.SCRAPER_TOKEN }}  # Make sure to use a secret token here
